sudo: false

env:
  - CABALVER=1.22 GHCVER=7.10.2
  - CABALVER=1.24 GHCVER=8.0.1
  - CABALVER=2.0 GHCVER=8.2.2
  - CABALVER=2.2 GHCVER=8.4.3
  - CABALVER=2.4 GHCVER=8.6.1

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
      - ghc-8.0.1
      - ghc-8.2.2
      - ghc-8.4.3
      - ghc-8.6.1
      - cabal-install-1.22
      - cabal-install-1.24
      - cabal-install-2.0
      - cabal-install-2.2
      - cabal-install-2.4

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - ghc --version
 - cabal --version
 - travis_retry cabal update
 - cabal install --enable-tests --only-dep

script:
- cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
